M48
; DRILL file {KiCad (7.0.0-0)} date Saturday, 25 February 2023 at 23:33:46
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-25T23:33:46+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(7.0.0-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
%
G90
G05
T1
X1.3Y-1.01
X1.3Y-3.28
X4.72Y-1.01
X4.72Y-3.28
T0
M30
